### ISSUE TITLE
I don't understand the price for the pro

### ISSUE THREAD

**Issue by t-n-y** [Arobases-Sylius-Plugins/ArobasesSyliusProfessionalCustomerPlugin#14]
Hi,

I tried the plugin, but there is one thing i can't understand. When i check the 'considerTaxesForProffessional' in the channel, i log in with a pro user, and i see the normal price. The only difference is that the tax part in the cart is equal to 0. 

Is it the normal behavior ? or maybe there is something i don't understand well. Thanks for the help

**Comment by camilleislasse** [comment]
This is normal behavior, what the plugin does is not to take into account the taxes when the customer is 'pro' and has checked the option in the channel.
Nothing is done so that he does not see the prices excluding tax in front

**Comment by t-n-y** [comment]
Ho ok, thank you for the feedback
